### ISSUE TITLE
SQL schema

### ISSUE THREAD

**Issue by posix4e** [planetlabs/datalake-api#1]
Do we have the schema for dynamo (and indexes) documented somewhere

**Comment by bcavagnolo** [comment]
There's no SQL schema. But the [metadata format](https://github.com/planetlabs/datalake-common#datalake-metadata), [dynamodb index scheme](https://github.com/planetlabs/datalake-common#index-design), and [dynamodb record format](https://github.com/planetlabs/datalake-common#datalake-record-format) used to support the index scheme are all specified in [datalake-common](https://github.com/planetlabs/datalake-common).

The code/spec that actually provisions the dynamodb index is not centralized at this time. Non-authoritative fragments live in the [test code for datalake-api](https://github.com/planetlabs/datalake-api/blob/master/tests/conftest.py#L24). The emerging authority is a cloudformations template is in our private ops repo. Clearly, it belongs in datalake-common. I just haven't factored it out yet. Also, I have some unresolved thoughts on what kind of automation to put in place around detecting schema changes at deploy time.
